

steam_machines = [
    'Steam Alloy Smelter',
    'Steam Fuser',
    'Steam Separator',
    'Steam Compressor',
    'High Pressure Steam Compressor',
    'Steam Squasher',
    'Steam Extractor',
    'High Pressure Steam Extractor',
    'Steam Forge Hammer',
    'High Pressure Steam Forge Hammer',
    'Steam Presser',
    'Steam Macerator',
    'High Pressure Steam Macerator',
    'Steam Grinder',
    'Steam Purifier',
    'Steam Blender',
    'High Pressure Alloy Smelter'
]


possible_machine_types = {
    'Acid Generator': 'not implemented',
    'Alloy Blast Smelter': 'not implemented',
    'Alloy Smelter': 'basic_gt',
    'Arc Furnace': 'basic_gt',
    'Arcane Infusion': 'not implemented',
    'Assembler': 'basic_gt',
    'Assemblyline Process': 'not implemented',
    'Autoclave': 'basic_gt',
    'Bacterial Vat': 'not implemented',
    'Baryonic Perfection': 'not implemented',
    'Bending Machine': 'basic_gt',
    'Bio Lab': 'not implemented',
    'Blast Furnace': 'not implemented',
    'Brewery': 'basic_gt',
    'COMET - Compact Cyclotron': 'not implemented',
    'Canner': 'basic_gt',
    'Centrifuge': 'basic_gt',
    'Chemical Bath': 'basic_gt',
    'Chemical Plant': 'not implemented',
    'Chemical Reactor': 'basic_gt',
    'Circuit Assembler': 'basic_gt',
    'Circuit Assembly Line': 'not implemented',
    'Clarifier': 'not implemented',
    'Coke Oven': 'not implemented',
    'Cold Trap': 'not implemented',
    'Combustion Generator Fuels': 'not implemented',
    'Component Assembly Line': 'not implemented',
    'Compressor': 'basic_gt',
    'Crafting (Shaped)': 'not implemented',
    'Crafting (Shapeless)': 'not implemented',
    'Crucible': 'not implemented',
    'Cryogenic Freezer': 'not implemented',
    'Cutting Machine': 'basic_gt',
    'DTPF': 'not implemented',
    'Degassing': 'not implemented',
    'Dehydrator': 'basic_gt',
    'Digester': 'basic_gt',
    'Dissolution Tank': 'not implemented',
    'Distillation Tower': 'not implemented',
    'Distillery': 'basic_gt',
    'Draconic Evolution Fusion Crafter': 'not implemented',
    'Electric Implosion Compressor': 'not implemented',
    'Electrolyzer': 'basic_gt',
    'Electromagnetic Polarizer': 'basic_gt',
    'Electromagnetic Separator': 'basic_gt',
    'Extractor': 'basic_gt',
    'Extreme Crafting (Shaped)': 'not implemented',
    'Extreme Crafting (Shapeless)': 'not implemented',
    'Extreme Diesel Engine Fuel': 'not implemented',
    'Extreme Heat Exchanger': 'not implemented',
    'Extruder': 'basic_gt',
    'Eye of Harmony': 'not implemented',
    'Fermenter': 'basic_gt',
    'Flocculation': 'not implemented',
    'Flotation Cell': 'not implemented',
    'Fluid Canner': 'basic_gt',
    'Fluid Extractor': 'basic_gt',
    'Fluid Heater': 'basic_gt',
    'Fluid Solidifier': 'basic_gt',
    'Forge Hammer': 'basic_gt',
    'Forming Press': 'basic_gt',
    'Furnace': 'not implemented',
    'Fusion Reactor': 'not implemented',
    'Gas Turbine Fuel': 'not implemented',
    'Godforge Upgrades': 'not implemented',
    'Helioflux Melting Core': 'not implemented',
    'Heliofusion Exoticizer': 'not implemented',
    'Heliothermal Plasma Fabricator': 'not implemented',
    'High Energy Laser Treatment': 'not implemented',
    'High Temperature Gas-cooled Reactor': 'not implemented',
    'Implosion Compressor': 'not implemented',
    'Isotope Decay': 'not implemented',
    'LFTR Gas Sparging': 'not implemented',
    'Large Boiler': 'not implemented',
    'Large Chemical Reactor': 'not implemented',
    'Large Naquadah Reactor': 'not implemented',
    'Laser Engraver': 'basic_gt',
    'Lathe': 'basic_gt',
    'Liquid Fluoride Thorium Reactor': 'not implemented',
    'Macerator': 'basic_gt',
    'Magic Energy Absorber Fuels': 'not implemented',
    'Magical Crafting (Shaped)': 'not implemented',
    'Magical Crafting (Shapeless)': 'not implemented',
    'Mass Fabrication': 'basic_gt',
    'Matter Amplifier': 'basic_gt',
    'Matter Fabricator': 'basic_gt',
    'Milling': 'not implemented',
    'Mixer': 'basic_gt',
    'Molecular Transformer': 'not implemented',
    'Multiblock Centrifuge': 'not implemented',
    'Multiblock Dehydrator': 'not implemented',
    'Multiblock Electrolyzer': 'not implemented',
    'Multiblock Mixer': 'not implemented',
    'Nano Forge': 'not implemented',
    'Naquadah Fuel Refinery': 'not implemented',
    'Naquadah Reactor MkI': 'not implemented',
    'Naquadah Reactor MkII': 'not implemented',
    'Naquadah Reactor MkIII': 'not implemented',
    'Naquadah Reactor MkIV': 'not implemented',
    'Naquadah Reactor MkV': 'not implemented',
    'Neutron Activator': 'not implemented',
    'Neutronium Compressor': 'not implemented',
    'Nuclear Fission': 'not implemented',
    'Nuclear Fuel Processing': 'not implemented',
    'Nuclear Salt Processing Plant': 'not implemented',
    'Oil Cracker': 'not implemented',
    'Ore Washer': 'basic_gt',
    'Ozonation': 'not implemented',
    'PCB Factory': 'not implemented',
    'Packager': 'basic_gt',
    'Plasma Arc Furnace': 'not implemented',
    'Plasma Generator Fuels': 'not implemented',
    'Precise Assembler': 'not implemented',
    'Primitive Blast Furnace': 'not implemented',
    'Printer': 'basic_gt',
    'Pyrolyse Oven': 'not implemented',
    'QC Components': 'not implemented',
    'Quantum Force Transformer': 'not implemented',
    'RTG': 'not implemented',
    'Radio Hatch Material List': 'not implemented',
    'Reactor Processing Unit': 'not implemented',
    'Replicator': 'basic_gt',
    'Research Station': 'not implemented',
    'Rock Breaker': 'basic_gt',
    'Rocket Engine Fuel': 'not implemented',
    'Scanner': 'basic_gt',
    'Semifluid Generator Fuels': 'not implemented',
    'Sifter': 'basic_gt',
    'Simple Dust Washer': 'basic_gt',
    'Slicer': 'basic_gt',
    'Solar Factory': 'not implemented',
    'Solar Tower': 'not implemented',
    'Source Chamber': 'not implemented',
    'Space Assembler': 'not implemented',
    'Space Mining': 'not implemented',
    'Space Projects': 'not implemented',
    'Target Chamber': 'not implemented',
    'Temperature Fluctuation': 'not implemented',
    'Thermal Boiler': 'not implemented',
    'Thermal Centrifuge': 'basic_gt',
    'Thermal Generator Fuels': 'not implemented',
    'Tool Casting Machine': 'deprecated',
    'Transcendent Plasma Mixer': 'not implemented',
    'Tree Growth Simulator': 'not implemented',
    'Unpackager': 'basic_gt',
    'Vacuum Freezer': 'not implemented',
    'Vacuum Furnace': 'not implemented',
    'Wiremill': 'basic_gt',
    'Zhuhai - Fishing Port': 'not implemented',
    'pH Neutralization': 'not implemented',
}

basic_gt_machines = [
    'Alloy Smelter',
    'Arc Furnace',
    'Assembler',
    'Autoclave',
    'Bending Machine',
    'Brewery',
    'Canner',
    'Centrifuge',
    'Chemical Bath',
    'Chemical Reactor',
    'Circuit Assembler',
    'Compressor',
    'Cutting Machine',
    'Dehydrator',
    'Digester',
    'Distillery',
    'Electrolyzer',
    'Electromagnetic Polarizer',
    'Electromagnetic Separator',
    'Extractor',
    'Extruder',
    'Fermenter',
    'Fluid Canner',
    'Fluid Extractor',
    'Fluid Heater',
    'Fluid Solidifier',
    'Forge Hammer',
    'Forming Press',
    'Laser Engraver',
    'Lathe',
    'Macerator',
    'Mass Fabrication',
    'Matter Amplifier',
    'Matter Fabricator',
    'Mixer',
    'Ore Washer',
    'Packager',
    'Printer',
    'Replicator',
    'Rock Breaker',
    'Scanner',
    'Sifter',
    'Simple Dust Washer',
    'Slicer',
    'Thermal Centrifuge',
    'Unpackager',
    'Wiremill'
]
