inputs: 
  - Enriched-Naquadah Oxide Mixture Dust = -0.266
outputs:
  - Enriched Naquadah Ingot
infinite_materials:
  - EU
  - Water
  - Fluorine
  - Antimony Dust
  - Ethanol
  - Phosphorus Comb
  - Seed Oil
  - Zinc Dust
  - Green Algae
  - Brown Algae
  - Salt Comb
restrictions:
  - Fluorine-Rich Waste Liquid <= 0
  - Waste Liquid <= 0
  - Zinc Sulfate Dust <= 0
  - Fluorspar Dust <= 0
  - Adamantine Dust <= 0
  - Trinium Sulphate Dust <= 0
weights:
  Enriched Naquadah Ingot: 1000
time: 1s
display_interval: 1s
table_gid: 769562043
max_singleblock_machines: 4
max_multiblock_machines: 1
unlocked_voltage_tier: LuV
default_voltage_tier: EV
maximal_energy_increase: 2
default_coil: Naquadah Alloy Coil
default_pipe_casing: Tungstensteel Pipe Casing
default_item_pipe_casing: Osmium Item Pipe Casing