inputs: 
  - Naquadah Oxide Mixture Dust = -0.1
outputs:
  - Naquadah Ingot
  - Hot Titanium Ingot
infinite_materials:
  - EU
  - Water
  - Oxygen
  - Hydrogen
  - Nitrogen
  - Chlorine
  - Fluorine
  - Carbon Dust
  - Antimony Dust
  - Ethanol
  - Phosphorus Comb
  - Sodium Dust
  - Seed Oil
  - Quicklime Dust
restrictions:
  - Titanium Trifluoride Dust <= 0
  - Hydrochloric Acid <= 0
weights:
  Naquadah Ingot: 1
  Hot Titanium Ingot: 0.01
time: 1s
display_interval: 1s
mode: Max
table_gid: 0
max_singleblock_machines: 4
max_multiblock_machines: 1
unlocked_voltage_tier: LuV
default_voltage_tier: EV
maximal_energy_increase: 1.5
default_coil: HSS-S Coil
default_pipe_casing: Tungstensteel Pipe Casing
default_item_pipe_casing: Osmium Item Pipe Casing