inputs: 
  - Crushed Bastnasite Ore = -2.26
outputs:
  - Samarium Dust
  - Terbium Dust
  - Lanthanum Dust
  - Cerium Dust
  - Neodymium Dust
infinite_materials:
  - EU
  - Water
  - Oxygen
  - Hydrogen
  - Nitrogen
  - Chlorine
  - Copper Dust
  - Fluorine
  - Saltpeter Dust
  - Carbon Dust
  - Vanadium Dust
  - Salt
  - Steam
  - Ammonia
  - Nitric Acid
  - Hydrochloric Acid
  - Methanol
  - Carbon Monoxide
  - Acetic Acid
  - Acetone
  - Raw Silicon Dust
restrictions:
  - Cerium Dioxide Dust <= 0
weights:
  Samarium Dust: 10
  Terbium Dust: 10
  Lanthanum Dust: 10
  Cerium Dust: 10
  Neodymium Dust: 10
time: 60s
display_interval: 60s
mode: Max
default_coil: HSS-G Coil
table_gid: 0
max_singleblock_machines: 8
max_multiblock_machines: 4
unlocked_voltage_tier: IV
default_voltage_tier: EV
maximal_energy_increase: 1.5