machine_types:
  air_intake_hatch:
  - name: Air Intake Hatch
    unlock_tier: IV
  algae_farm:
  - name: Algae Farm
    unlock_tier: MV
  alloy_smelter:
  - name: Alloy Smelter
    unlock_tier: ULV
  autoclave:
  - name: Autoclave
    unlock_tier: LV
  bending_machine:
  - name: Bending Machine
    unlock_tier: LV
  blast_furnace:
  - name: Blast Furnace
    multiblock: True
    unlock_tier: LV
    valid_machine_options: 
    - coils
  centrifuge:
  - name: Centrifuge
    unlock_tier: LV
    avoid_to_use: True
  - name: Industrial Centrifuge
    speedup: 2.25
    energy_multiplier: 0.9
    base_parallels: 0
    parallels_per_voltage_tier: 6
    multiblock: True
    unlock_tier: EV
  chemical_bath:
  - name: Chemical Bath
    unlock_tier: LV
  - name: Ore Washing Plant (Chemical Bath)
    speedup: 5.0
    base_parallels: 0
    parallels_per_voltage_tier: 4
    multiblock: True
    unlock_tier: EV
  chemical_plant:
  - name: ExxonMobil Chemical Plant
    multiblock: True
    unlock_tier: MV
    valid_machine_options: 
    - coils
    - pipe_casings
  chemical_reactor:
  - name: Chemical Reactor
    unlock_tier: LV
    avoid_to_use: True
  - name: Large Chemical Reactor
    multiblock: True
    unlock_tier: HV
  combustion_generator:
  - name: Advanced Combustion Generator
    unlock_tier: MV
  - name: Turbo Combustion Generator
    unlock_tier: HV
  - name: Large Combustion Engine
    multiblock: True
    unlock_tier: EV
  compressor:
  - name: Compressor
    unlock_tier: LV
  - name: Large Electric Compressor
    speedup: 2.0
    energy_multiplier: 0.9
    base_parallels: 0
    parallels_per_voltage_tier: 2
    multiblock: True
    unlock_tier: EV
  crafting:
  - name: Crafting
  dehydrator:
  - name: Dehydrator
    unlock_tier: EV
  digester:
  - name: Digester
    multiblock: True
    unlock_tier: IV
  dissolution_tank:
  - name: Dissolution Tank
    multiblock: True
    unlock_tier: EV
  distillation_tower:
  - name: Distillation Tower
    multiblock: True
    unlock_tier: HV
  - name: Dangote Distillus (Distillation Tower)
    speedup: 3.5
    base_parallels: 12
    multiblock: True
    unlock_tier: IV
  distillery:
  - name: Distillery
    unlock_tier: LV
  - name: Dangote Distillus (Distillery)
    speedup: 2.0
    base_parallels: 0
    parallels_per_voltage_tier: 8
    multiblock: True
    unlock_tier: IV
  electromagnetic_separator:
  - name: Electromagnetic Separator
    unlock_tier: LV
  - name: Magnetic Flux Exhibitor
    multiblock: True
    unlock_tier: IV
    valid_machine_options: 
    - electromagnets
  electrolyzer:
  - name: Electrolyzer
    unlock_tier: LV
    avoid_to_use: True
  - name: Industrial Electrolyzer
    speedup: 2.8
    energy_multiplier: 0.9
    base_parallels: 0
    parallels_per_voltage_tier: 2
    multiblock: True
    unlock_tier: IV
  extruder:
  - name: Extruder
    unlock_tier: LV
  - name: Industrial Extrusion Machine
    speedup: 3.5
    base_parallels: 0
    parallels_per_voltage_tier: 4
    multiblock: True
    unlock_tier: IV
  fluid_canner:
  - name: Fluid Canner
    unlock_tier: LV
  - name: TurboCan Pro (Fluid Canner)
    speedup: 2.0
    base_parallels: 0
    parallels_per_voltage_tier: 8
    multiblock: True
    unlock_tier: HV
  fluid_extractor:
  - name: Fluid Extractor
    unlock_tier: LV
  fluid_heater:
  - name: Fluid Heater
    unlock_tier: LV
  - name: Thermal Heating Device (Fluid Heater)
    speedup: 2.2
    energy_multiplier: 0.9
    base_parallels: 0
    parallels_per_voltage_tier: 8
    multiblock: True
    unlock_tier: IV
  fluid_solidifier:
  - name: Fluid Solidifier
    unlock_tier: LV
  forge_hammer:
  - name: Forge Hammer
    unlock_tier: LV
  gas_turbine:
  - name: Advanced Gas Turbine
    efficiency: 0.9
    unlock_tier: MV
  - name: Turbo Gas Turbine
    efficiency: 0.85
    unlock_tier: HV
  - name: Large Gas Turbine
    multiblock: True
    unlock_tier: EV
  industrial_coke_oven:
  - name: Industrial Coke Oven
    base_parallels: 30
    multiblock: True
    unlock_tier: EV
  macerator:
  - name: Macerator
    unlock_tier: LV
  - name: Industrial Maceration Stack
    speedup: 1.6
    base_parallels: 0
    parallels_per_voltage_tier: 2
    multiblock: True
  - name: Industrial Maceration Stack (Upgraded)
    speedup: 1.6
    base_parallels: 0
    parallels_per_voltage_tier: 8
    multiblock: True
    unlock_tier: EV
  mixer:
  - name: Mixer
    unlock_tier: LV
    avoid_to_use: True
  - name: Industrial Mixing Machine (Mixer)
    speedup: 3.5
    base_parallels: 0
    parallels_per_voltage_tier: 8
    multiblock: True
    unlock_tier: IV
  naquadah_reactor_1:
  - name: Naquadah Reactor Mark I
    unlock_tier: EV
  naquadah_reactor_2:
  - name: Naquadah Reactor Mark II
    unlock_tier: IV
  naquadah_reactor_3:
  - name: Naquadah Reactor Mark III
    unlock_tier: LuV
  naquadah_reactor_4:
  - name: Naquadah Reactor Mark IV
    unlock_tier: ZPM
  naquadah_reactor_5:
  - name: Naquadah Reactor Mark V
    unlock_tier: UV
  neutron_activator:
  - name: Neutron Activator
    multiblock: True
    unlock_tier: LuV
  oil_cracker:
  - name: Oil Cracking Unit
    multiblock: True
    unlock_tier: HV
    valid_machine_options: 
    - coils
  pyrolyse_oven:
  - name: Pyrolyse Oven
    multiblock: True
    unlock_tier: MV
    valid_machine_options: 
    - coils
  sifter:
  - name: Sifter
    unlock_tier: LV
  - name: Large Sifter Control Block
    speedup: 5.0
    energy_multiplier: 0.75
    base_parallels: 0
    parallels_per_voltage_tier: 4
    multiblock: True
    unlock_tier: HV
  simple_washer:
  - name: Simple Dust Washer
    unlock_tier: LV
  - name: Ore Washing Plant (Simple Washer)
    speedup: 5.0
    base_parallels: 0
    parallels_per_voltage_tier: 4
    multiblock: True
    unlock_tier: EV
  thermal_centrifuge:
  - name: Thermal Centrifuge
    unlock_tier: LV
  - name: Large Thermal Refinery
    speedup: 2.5
    energy_multiplier: 0.8
    base_parallels: 0
    parallels_per_voltage_tier: 8
    multiblock: True
    unlock_tier: EV
  vacuum_freezer:
  - name: Vacuum Freezer
    multiblock: True
    unlock_tier: HV